### ISSUE TITLE
move to .yaml for config?

### ISSUE THREAD

**Issue by vivekbhr** [deeptools/HiCBrowser#22]
Current config (.ini) file has it's own format, while yaml is a popular and easy to use format. Plus I am not sure if current config allows a hierarchy in the dictionary keys obtained after parsing. If we have a hierarchy of keys we can merge the gene config and browser config file into one and then we require only one config at browser startup.

For example:

```
gene_view:
    boundaries_bed:
        file: /path/to/file
        title: TADs
        color: red
    genes:
        file: /data/test/hicBrowser/GRCm38_genes2.bed 
        title: genes
        color: darkblue
region_view:
    hic_file:
        file: /data/test/hicBrowser/mF1216_merged_10k.h5 
        title: mF1216
        colormap: RdYlBu_r
        depth: 1000000
    bigwig:
        file: /data/test/hicBrowser/H3k4me3.bw 
        title: H3K4me3

```
